### ISSUE TITLE
object 'model' not found

### ISSUE THREAD

**Issue by NatPRoach** [adnaniazi/tailfindr#1]
Hello,
I'm running in to trouble running tailfindr on my data. I'm getting the following in the log file:
```
● Analyzing a single Fast5 file to assess if your data
  is in an acceptable format...
Error in explore_basecaller_and_fast5type(fast5_files_list[1]) :
  object 'model' not found
Calls: find_tails -> explore_basecaller_and_fast5type
Execution halted
```
Based on your README, looking through my fast5 files in HDFView, and reading the relevant sections of the code a bit, I believe this to be because my fast5 files already have a Basecall_1D_000 field prior to basecalling with albacore with a name field that reads "MinKNOW-Live-Basecalling". Basecalling in albacore produces a Basecall_1D_001 field with a name field "ONT Albacore Sequencing Software". I'm attempting to get the raw fast5 files that weren't basecalled prior, but I thought I'd open an issue to ask if there are any plans to support basecalling in the Basecall_1D_001 field in the future. Thank you.

**Comment by adnaniazi** [comment]
Hello Nathan,

Thank you for trying tailfindr.

Can you please send me some Fast5 files (around 10 or 20) so that I can work on patching tailfindr to handle your particular dataset. You can email them to me on adnan.niazi@uib.no. 

Thanks.

**Comment by adnaniazi** [comment]
Thank you for providing me the FAST5 files. I have now patched tailfindr to handle any basecall_group.

To use the new revised tailfindr, please follow these steps:
1. Uninstall tailfindr from your R library
2. Install it again using devtools:
`devtools::install_github("adnaniazi/tailfindr")`
3. For your particular dataset, here is how you should now use tailfindr:
`df <- find_tails(fast5_dir='path/to/your/basecalled/fast5/files', save_dir='/any/directory/where/results/should/be/stored', csv_filename = 'tails.csv', basecall_group = 'Basecall_1D_001', save_plots = TRUE, plotting_library = 'rbokeh')`

The important thing to note here is that now you have specified 'Basecall_1D_001' as your basecall group, i.e., the level (in the FAST5 hierarchy) from which tailfindr should fetch basecalls. Previously, tailfindr was hardcoded to only look in the Basecall_1D_000 level of the FAST5 hierarchy, but now users can change it by passing the `basecall_group` parameter to the find_tails function. 

Please let me know if this solved your problem. Also let me know, if I can distribute a few of your reads in my package to demonstrate your particular use case.

Thanks.

**Comment by NatPRoach** [comment]
Hi Adnan,
Thank you for the fast turn around! I will follow your instructions and let you know how it works ASAP. As far as distributing a few of the reads, that’s fine with me.

All the best,
Nathan Roach
PhD Candidate
J. Kim & J. Taylor Labs
nroach2@jhu.edu<mailto:nroach2@jhu.edu>

**Comment by martynakgajos** [comment]
I am still experiencing similar problem:

> ────────────────────────────────────────────────────────────────────────────────
> ── Started tailfindr (version 0.1.0) ───────────────────────────────────────────
> ────────────────────────────────────────────────────────────────────────────────
> ☰ You have configured tailfindr as following:
> ❯ fast5_dir:         path/rawReads/
> ❯ save_dir:          path/Results/
> ❯ csv_filename:      tails.csv
> ❯ num_cores:         40
> ❯ basecall_group:    Basecall_1D_000
> ❯ save_plots:        FALSE
> ❯ plot_debug_traces: FALSE
> ❯ plotting_library:  rbokeh
> ── Processing started at 2019-08-20 17:21:39 ───────────────────────────────────
> ● Searching for all Fast5 files...
>   Done! Found 108 Fast5 files.
> ● Analyzing a single Fast5 file to assess if your data 
>   is in an acceptable format...
> Error in explore_basecaller_and_fast5type(fast5_files_list[1], basecall_group = basecall_group) : 
>   object 'model' not found
>

**Comment by adnaniazi** [comment]
Can you please send me a few of your fast5 files. I will look into it to see what is causing the error. You can email them to me on adnaniazi@gmail.com.

**Comment by manburst** [comment]
Hello sir, I also facing a similar issue. I have followed the instruction as you described above but it still not working. The result when I run with `basecall_group = 'Basecall_1D_001'`
give me a result
` Error in x$exists(name) : CHAR() can only be applied to a 'CHARSXP', not a 'NULL'`
and when I run with this
`basecall_group = 'Basecall_1D_000'`
it gives me
`x Fatal error! Your data has been basecalled with MinKNOW
    live basecalling which currently does not save the
    Events/Move table in the Analyses/Basecall_1D_000 section of
    the FAST5 file. You should rebasecall your FAST5 files using 
    standalone Guppy or Albacore, and then use tailfindr on the 
    rebasecalled files. Please adjust the value of basecall_group
    parameter in such a case, so that tailfindr can find the 
    Events/Move table in the specified basecall_group. You can
    check which basecall_group the Event/Move is residing by
    opening your FAST5 file in HDFView.`

**Comment by sunsetyerin** [comment]
Hi @adnaniazi, I'm having the same error here 
`df <- find_tails(fast5_dir = "/path/", save_dir = "/path/", csv_filename = "rna_tail.csv", basecall_group = "Basecall_1D_001", num_cores = 50)
────────────────────────────────────────────────────────────────────────────────
── Started tailfindr (version 0.1.0) ───────────────────────────────────────────
────────────────────────────────────────────────────────────────────────────────
☰ You have configured tailfindr as following:
❯ fast5_dir:         /path
❯ save_dir:          /path/
❯ csv_filename:      rna_tail.csv
❯ num_cores:         50
❯ basecall_group:    Basecall_1D_001
❯ save_plots:        FALSE
❯ plot_debug_traces: FALSE
❯ plotting_library:  rbokeh
── Processing started at 2022-05-06 18:31:51 ───────────────────────────────────
● Searching for all Fast5 files...
  Done! Found 637 Fast5 files.
● Analyzing a single Fast5 file to assess if your data 
  is in an acceptable format...
Error in explore_basecaller_and_fast5type(fast5_files_list[1], basecall_group = basecall_group) : 
  object 'model' not found`
  
Can you also look into my fast5 files please?

**Comment by adnaniazi** [comment]
Hi @sunsetyerin,

I have checked your FAST5 files and it seems like you basecalled your data during the run. This kind of basecalling only outputs raw FAST5 files and basecalled data as separate FASTQ files. What tailfindr needs are basecalled FAST5 files that contains the basecalling information inside the FAST5 file itself -- and not in a separate FASTQ file.

Please use the FAST5 files produced by your PromethION run as input to a standalone installation of Guppy, and re-basecall your data and remember to include the `--fast5_out` option in the basecalling command. This step will rebasecall the data, and generate a new set of FAST5 files with basecalling information included in the FAST5 files. Use these new basecalled FAST5 files as input to tailfindr and it would work. 

Also, before running tailfindr makes sure that you have the VBZ plugin installed. Here si how to do it:

Download (for your operating system) and extract the VBZ plugin:

[https://github.com/nanoporetech/vbz_compression/releases/tag/v1.0.1
](https://github.com/nanoporetech/vbz_compression/releases/tag/v1.0.1)

Then assuming you are using Linux export `HDF5_PLUGIN_PATH` plugin path like this:

`export HDF5_PLUGIN_PATH=/bla/bla/bla_path/vbz/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin`

(Change the path yourself in the above command)
