### ISSUE TITLE
Expected analysis time

### ISSUE THREAD

**Issue by callumparr** [adnaniazi/tailfindr#11]
I am running tailfindr through master of pores nextflow pipeline. So far it has taken roughly 6hrs to run through 6% of the data with 24 available CPUs. I was unsure what would be the expected compute time for direct RNA libraries (roughly 1 to 2 million reads). 

This seems slow and I am unsure if I am doing something wrong ?

**Comment by adnaniazi** [comment]
Sorry, I haven't done any benchmarking, but it is a rather slow algorithm, and the code isn't well-optimized.

**Comment by callumparr** [comment]
Cool no probs I will be patient. Thank you. I think I may run more interactively later to look at visual plotting of tails, seems nice feature.

**Comment by adnaniazi** [comment]
Only generate plots for a few reads, not for the whole dataset. If you generate the plots for all 1-2million reads the dataset, it will be very very slow as these plots take a lot of time to generate.

**Comment by callumparr** [comment]
Based on this CMD it should not plot tails? 

```
#!/bin/bash -ue
R --slave -e "library(tailfindr); find_tails(fast5_dir = './' , save_dir = './', basecall_group = 'Basecall_1D_001', csv_filename = 'Day2_09_DRS_NanoPreprocess-FAL86574_pass_94dbee5f_67_findr.csv', num_cores = 22)"
master_of_pores/NanoTail/work/9e/5023fb9586f94ca95671b3bc944a6c/.command.sh (END)
```

The plot is FALSE I think ?

**Comment by adnaniazi** [comment]
Yes. That is the correct command. Plotting is set to False by default.

**Comment by callumparr** [comment]
According to the log file with processing start time and process end time. Its about 12 mins for one mutli fast5 file (default 4000 reads).

**Comment by adnaniazi** [comment]
The timing seems about right to me. The run time also depends on the length of the reads. The longer the reads, the more time it would it take to process that read. This is because with the introduction of Guppy, ONT removed much of the useful basecalling information that used to be present in Albacore's Fast5 output. So tailfindr needs to manually recreate this information to be able to accurately calculate the tail length. This is slow.

**Comment by callumparr** [comment]
Thank you for the help and the tool
