### ISSUE TITLE
Add support for VBZ compression

### ISSUE THREAD

**Issue by CDieterich** [adnaniazi/tailfindr#13]
Guppy lately uses VBZ compression for FAST5 files. I tried tailfindR on VBZ compressed files and it does not work.
If I repack them to gzip compression the same files work.

**Comment by adnaniazi** [comment]
Thank you for using tailfindr. I would love to make tailfindr work natively on VBZ-compressed fast5 file but I don't know how to decompress a VBZ-compressed fast5 file from within R. The only workaround, for now, is to decompress the files yourself (as you did) and then use tailfindr on the decompressed files. It is a big pain, I know.

**Comment by CDieterich** [comment]
Dear @adnaniazi,
this here seems to be related
https://github.com/nanoporetech/vbz_compression/issues/5

**Comment by adnaniazi** [comment]
Hi @CDieterich,

Thank you for pointing out the resource. It is very helpful. 

I didn't had any VBZ compressed data, so I used ONTs VBZ compression tool to vbz-compress the legacy fast5 files I already had, and then gave it to tailfindr as input. It seemed to work with tailfindr. But I am not sure if the compression really worked at my end. The compressed files are even bigger in size than the uncompressed ones.
![Screen Shot 2020-06-26 at 11 21 02 AM](https://user-images.githubusercontent.com/6848063/85842149-84910100-b79f-11ea-977d-a3a5e02f959e.png)

I want to try out tailfindr with one of your VBZ compressed files that tailfindr failed on. Would it possible for you to share one of your VBZ-compressed fast5 file. If yes, then you can email it to me on adnaniazi@gmail.com. 
Thank you.

**Comment by adnaniazi** [comment]
Installing VBZ plugin (https://github.com/nanoporetech/vbz_compression/releases) for your particular operating solves the problem.
