### ISSUE TITLE
poly A

### ISSUE THREAD

**Issue by amitblum** [adnaniazi/tailfindr#14]
Hello 
I got the following message:
"
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/apps/RH7U2/gnu/R/3.5.1/lib64/R/library/hdf5r/libs/hdf5r.so':
  libhdf5.so.103: cannot open shared object file: No such file or directory
"
How should I solve it?
Thanks
Amit

**Comment by adnaniazi** [comment]
Hi,

I cannot pinpoint the exact reason for the error, but I can give you pointers on what to try to debug it:
1. Please ensure that the Fast5 files used with tailfindr are not vbz compressed. You can check if tailfindr works with the FAST5 files provided with the tailfindr by running the example code provided in the repo README. These files are not VBZ compressed. So if tailfindr works with the packaged FAST5 files, then it is your VBZ compressed files that are the source of problem. In that case, you should change the compression level of VBZ files to the legacy gzip.

>  h5repack -f GZIP=1 input.fast5 output.fast5
https://github.com/nanoporetech/vbz_compression

2. Ensure that any of the FAST5 files you are using in tailfindr is not open in any other software, such as HDFView. 

3. If the above two steps do not solve the problem, then reinstall libhdf5-dev and tailfindr.

Hope any of it will help.

Adnan

**Comment by adnaniazi** [comment]
You can also try to install the appropriate VBZ plugin for the system that you are using tailfindr on:
https://github.com/nanoporetech/vbz_compression/releases/tag/v1.0.1

This will solve the problem of tailfindr not reading the VBZ-compressed files.
