### ISSUE TITLE
Empty Result in gregor_polya_base_end branch

### ISSUE THREAD

**Issue by pynie1** [adnaniazi/tailfindr#17]
Hi,Adnan,
      Thanks for tailfiner.I have two question:
      1.I get an empty result after I install by devtools::install_github("adnaniazi/tailfindr", ref ="gregor_polya_base_end").
result is below:
read_id,read_type,tail_is_valid,tail_start,tail_end,samples_per_nt,tail_length,tail_start_base_index,tail_end_base_index,polya_tail_fasta_seq,full_read_fasta_seq,file_path
read_e5fe1535-10fe-4f60-8871-54d89f3d76a7,,,,,,,,,,,\~/workspace/PAF15853_pass_39ad6f02_2.fast5
read_627cd567-e82e-4fbe-905e-f86aeee214cb,,,,,,,,,,,\~/workspace/PAF15853_pass_39ad6f02_2.fast5
read_62cf835e-d994-42ae-8ea5-fdc51b525997,,,,,,,,,,,\~/workspace/PAF15853_pass_39ad6f02_2.fast5
before I installed I can get a non-empty result,:
read_id,read_type,tail_is_valid,tail_start,tail_end,samples_per_nt,tail_length,file_path
627cd567-e82e-4fbe-905e-f86aeee214cb,invalid,FALSE,,,10.32,,\~/workspace/PAF15853_pass_39ad6f02_2.fast5
62cf835e-d994-42ae-8ea5-fdc51b525997,polyA,FALSE,,,9.18,,\~/workspace/PAF15853_pass_39ad6f02_2.fast5
20dd1d1a-a1d4-47d1-9693-877ed8d4241b,polyA,FALSE,,,10.88,,\~/workspace/PAF15853_pass_39ad6f02_2.fast5

I notice that the read_id in new result has a string named "read_" before every real read_id.Did I do something wrong while installing?could you please give me some advice?
    2.I got some warnings while using tailfiner.The log is below:

────────────────────────────────────────
─ Started tailfindr (version 0.1.0) ──────────────────────
────────────────────────────────────────
☰ You have configured tailfindr as following:
❯ fast5_dir:         ~/workspace
❯ save_dir:          ~/ttt
❯ csv_filename:      cdna_tails2.csv
❯ num_cores:         2
❯ basecall_group:    Basecall_1D_001
❯ save_plots:        TRUE
❯ plot_debug_traces: FALSE
❯ plotting_library:  rbokeh
─ Processing started at 2020-12-15 16:41:14 ──────────────────
● Searching for all Fast5 files...
  Done! Found 1 Fast5 files.
● Analyzing a single Fast5 file to assess if your data 
  is in an acceptable format...
  ✔ The data has been basecalled using Guppy.
  ✔ Flipflop model was used during basecalling.
  ✔ The reads are packed in multi-fast5 file(s).
  ✔ The experiment type is DNA, so we will search
    for both poly(A) and poly(T) tails.
  ✔ The reads are 1D reads.
● Starting a parallel compute cluster...
  Done!
● Discovering reads in the 1 multifast5 files...
  Done! Found 25 reads
● Searching for Poly(A) and Poly(T) tails...
  Processing chunk 1 of 1
  |======================================================================| 100%
● Formatting the tail data...
  Done!
● Saving the data in the CSV file...
  Done! Below is the path of the CSV file:
  ~/ttt/cdna_tails2.csv
● A logfile containing all this information has been saved in this path: 
  ~/ttt/2020-12-15_16-41-14_tailfinder.log
─ Processing ended at 2020-12-15 16:41:25 ───────────────────
✔ tailfindr finished successfully!
Warning message:
`cols` is now required when using unnest().
Please use `cols = c(read_id, read_type, tail_is_valid, tail_start, tail_end, samples_per_nt, 
    tail_length, file_path, has_precise_boundary)` 
\# A tibble: 25 x 8
   read_id read_type tail_is_valid tail_start tail_end samples_per_nt
   <chr>   <chr>     <lgl>              <dbl>    <dbl>          <dbl>
 1 e5fe15… polyT     TRUE                 905     1615           8.09
 2 627cd5… polyT     TRUE                2370     2570          10.3 
 3 62cf83… polyA     FALSE                 NA       NA           9.18
 4 20dd1d… polyA     FALSE                 NA       NA          10.9 
 5 6f6be3… invalid   FALSE                 NA       NA           9.08
 6 15e55d… polyT     TRUE                2030     2280           9.55
 7 ef87cf… invalid   FALSE                 NA       NA          10.6 
 8 f08994… invalid   FALSE                 NA       NA          10.0 
 9 3d43e3… polyA     FALSE                 NA       NA           9.48
10 837ca0… polyT     TRUE                1575     2405           8.74
\# … with 15 more rows, and 2 more variables: tail_length <dbl>,
\#   file_path <chr>

I can not understand the warning messages:
########
Warning message:
`cols` is now required when using unnest().
Please use `cols = c(read_id, read_type, tail_is_valid, tail_start, tail_end, samples_per_nt, 
    tail_length, file_path, has_precise_boundary)` 
#############
I need your help.
thank you.

**Comment by adnaniazi** [comment]
Hi,

Thank you for using tailfindr.

Can you please send me on (adnaniazi@gmail.com) some of your basecalled fast5 files to help me troubleshoot the problem. Thanks.

Adnan

**Comment by pynie1** [comment]
Hi,@adnaniazi ,
     Sorry for the late reply.I've sent you my fast5 file.

**Comment by adnaniazi** [comment]
Hi Pynie1,

Thanks for sending the Fast5 files. 

I have now corrected the branch. It will now produce the correct output (see the attached zip file).

As your data is cDNA, you will have both polyA and poly(T) tails in your data. However, since polyA tails in cDNA are sequenced at the very end, and most of your polyA reads did not reach this end, therefore, your polyA tail reads do not have polyA tails because the reads were most probably ejected from the pore before the sequencing the poly(A) tails. That's why all of your polyA tails are invalid i.e., they do not have a polyA tail at all. 

If you have more questions, we can help you out. Feel free to ask them.

Adnan


[Archive.zip](https://github.com/adnaniazi/tailfindr/files/5709064/Archive.zip)

**Comment by adnaniazi** [comment]
Hi Pynie1,

You must basecall your data with 
`--trim_strategy none`

This ensures that the adaptors (which tailfindr uses to home in to the poly(A)/(T) regions) are not trimmed.

Adnan
