### ISSUE TITLE
No plot show

### ISSUE THREAD

**Issue by manburst** [adnaniazi/tailfindr#19]
Hello sir, I have followed the installation manual and try to plot with the example data set
`library(tailfindr) 
library(rbokeh)
library(hdf5r)
library(rhdf5)
library(Rhdf5lib)
df <- find_tails(fast5_dir = system.file('extdata', 'cdna', package = 'tailfindr'),
                 save_dir = '~/Downloads',
                 csv_filename = 'cdna_tails.csv',
                 num_cores = 2,
                 save_plots = TRUE,
                 plotting_library = 'rbokeh')`
The code has run succesfully. The results are in its destination path, also the plots. However, the plot results is not showing when run finished.
Thanks in advance.

**Comment by adnaniazi** [comment]
Hi,

Please refer to the workaround mentioned in this [issue](https://github.com/adnaniazi/tailfindr/issues/15).

Adnan

**Comment by manburst** [comment]
Thanks!
