### ISSUE TITLE
problem with version of hdf5

### ISSUE THREAD

**Issue by lucacozzuto** [adnaniazi/tailfindr#2]
Dear developer, I got this error, while trying to install the package.

Can you help me on overcome this, please?

```
Found hdf5 with version: 1.8.12
configure: error: The version of hdf5 installed on your system is not sufficient. Please ensure that at least version 1.8.13 is installed
ERROR: configuration failed for package 'hdf5r'
* removing '/usr/lib64/R/library/hdf5r'
Error: Failed to install 'tailfindr' from GitHub:
  (converted from warning) installation of package 'hdf5r' had non-zero exit status
Execution halted
The command '/bin/sh -c Rscript -e "devtools::install_github(\"adnaniazi/tailfindr\")"' returned a non-zero code: 1
```

**Comment by adnaniazi** [comment]
Dear Luca,
tailfindr has a dependency on hdf5r package, and hdf5r package requires the latest version of HDF5 library to already installed on your system. It seems like your system has v1.8.12 installed on it. You need to update your system's HDF5 library. Please see the HDF5 library installation section on tailfindr github page. Hopefully, after updating your HDF5 library from v1.8.12 to v1.8.13, and installing tailfindr will work.
