### ISSUE TITLE
Find tail and plot specific read in multi FAST5 file

### ISSUE THREAD

**Issue by manburst** [adnaniazi/tailfindr#22]
Hello sir,
Now I am working on nanopore project with multi FAST5. Due to my multi FAST5 file is contain 4000 reads in there and I interested some reads in there and want to plot the current of them. Is anyway to plot and find the tail of specific reads in multi fast5 file because I running on my pc and plot files will consume my space, also too long running time.
Thanks in advance.

**Comment by adnaniazi** [comment]
You can split multifast5 into single fast5 files using ont-fast-api (https://github.com/nanoporetech/ont_fast5_api) from Oxford nanopore, and then give only those single fast5s for which you need the plots as input to tailfindr.
