### ISSUE TITLE
Empty ggplotted plots

### ISSUE THREAD

**Issue by nemitheasura** [adnaniazi/tailfindr#23]
Hi,
I encountered an issue while using ggplot2 as plotting library. The .png files are present in output directory, but they are empty. 

Here is the command I used:

`df <- find_tails(fast5_dir = '/home/nemi/analysis/fast5_subset/guppy_output/workspace',
                  save_dir = '/home/nemi/analysis/fast5_subset/tailfindr',
                  csv_filename = 'tails_tailfindr.csv',
                  num_cores = 10,
                  save_plots = TRUE,
                  plotting_library = 'ggplot2')`

It produced all the expected output files contained within the output directory (logfile, table & plots with "png" extensions). Here is the content of produced logfile - it seems like everything went allright. 

──────────Started tailfindr (version 0.1.0) ───────────────────────
☰ You have configured tailfindr as following:
> fast5_dir:        /home/nemi/analysis/fast5_subset/guppy_output/workspace
> save_dir:          /home/nemi/analysis/fast5_subset/tailfindr
> csv_filename:      tails_tailfindr.csv
> num_cores:         10
> basecall_group:    Basecall_1D_000
> save_plots:        TRUE
> plot_debug_traces: FALSE
> plotting_library:  ggplot2
── Processing started at 2021-07-15 12:47:04 ─────────────────────────────────────────────────────────
• Searching for all Fast5 files...
  Done! Found 6 Fast5 files.
• Analyzing a single Fast5 file to assess if your data 
  is in an acceptable format...
  [32m✓[39m The data has been basecalled using Guppy.
  [32m✓[39m Flipflop model was used during basecalling.
  [32m✓[39m Every read is in a single fast5 file of its own.
  [32m✓[39m The experiment type is RNA, so we will search
    for poly(A) tails.
  [32m✓[39m The reads are 1D reads.
• Starting a parallel compute cluster...
  Done!
• Searching for Poly(A) tails...
  Processing chunk 1 of 1
• Formatting the tail data...
  Done!
• Saving the data in the CSV file...
  Done! Below is the path of the CSV file:
  /home/nemi/analysis/fast5_subset/tailfindr/tails_tailfindr.csv
• A logfile containing all this information has been saved in this path: 
  /home/nemi/analysis/fast5_subset/tailfindr/2021-07-15_12-47-04_tailfinder.log
── Processing ended at 2021-07-15 12:47:07 
[32m✓[39m tailfindr finished successfully!

But something went wrong. At first I thought, that this might be the problem with x11 device, so I defined options manually
`options(bitmapType='cairo')`

But this did not solve the problem. When looking through the output table I found out, that the problem is deeper than the plotting itself. The results table does not contain all the informations it should have. Here is the content of my "tails_tailfindr.csv" file:

read_id,tail_start,tail_end,samples_per_nt,tail_length,file_path
,,,,,/home/nemi/analysis/fast5_subset/guppy_output/workspace/cea0563c-0101-41f1-8133-ed77ee5f9a46.fast5
,,,,,/home/nemi/analysis/fast5_subset/guppy_output/workspace/725fbbe7-274e-4bb9-8b32-41f63a766acd.fast5
,,,,,/home/nemi/analysis/fast5_subset/guppy_output/workspace/dbc80231-9152-47fd-b358-fe2ba73460d2.fast5
,,,,,/home/nemi/analysis/fast5_subset/guppy_output/workspace/7306f332-3f4f-4657-b354-509bc6744cf6.fast5
,,,,,/home/nemi/analysis/fast5_subset/guppy_output/workspace/0d88e68b-ceae-4bed-a882-76042bd2782a.fast5
,,,,,/home/nemi/analysis/fast5_subset/guppy_output/workspace/9bd5e19a-2766-4290-9aed-76d603d77a42.fast5

On the other hand, if I will choose rbokeh as plotting library, it returns valid html files (populated with squiggles) and following table: 

read_id,tail_start,tail_end,samples_per_nt,tail_length,file_path
725fbbe7-274e-4bb9-8b32-41f63a766acd,6330,8655,26.26,83.55,/home/nemi/analysis/fast5_subset/guppy_output/workspace/725fbbe7-274e-4bb9-8b32-41f63a766acd.fast5
7306f332-3f4f-4657-b354-509bc6744cf6,5406,8431,26.44,109.42,/home/nemi/analysis/fast5_subset/guppy_output/workspace/7306f332-3f4f-4657-b354-509bc6744cf6.fast5
9bd5e19a-2766-4290-9aed-76d603d77a42,7820,10895,27.81,105.55,/home/nemi/analysis/fast5_subset/guppy_output/workspace/9bd5e19a-2766-4290-9aed-76d603d77a42.fast5
dbc80231-9152-47fd-b358-fe2ba73460d2,4401,8051,27.58,127.32,/home/nemi/analysis/fast5_subset/guppy_output/workspace/dbc80231-9152-47fd-b358-fe2ba73460d2.fast5
cea0563c-0101-41f1-8133-ed77ee5f9a46,5307,8232,25.82,108.28,/home/nemi/analysis/fast5_subset/guppy_output/workspace/cea0563c-0101-41f1-8133-ed77ee5f9a46.fast5
0d88e68b-ceae-4bed-a882-76042bd2782a,5647,5947,23.38,7.83,/home/nemi/analysis/fast5_subset/guppy_output/workspace/0d88e68b-ceae-4bed-a882-76042bd2782a.fast5

I thought that you might want to know that there is such an issue and fix it. 

Best regards,
N.

**Comment by adnaniazi** [comment]
Hi, Thank you for reporting the issue. I will fix it in August. For now, just use the rbokeh option.
Adnan

**Comment by nemitheasura** [comment]
Hello,
thank you very much. I am looking forward for upcoming updates. 

Best,
N.

**Comment by adnaniazi** [comment]
Hi,

I had a chance of looking at your issue. The ggplot option works fine at my end. Can you please try to Uninstall tailfindr and install it again. It should work.

Best,
Adnan
