### ISSUE TITLE
performance following minimal working example

### ISSUE THREAD

**Issue by jon-xu** [adnaniazi/tailfindr#29]
Hi Adnan,

Thanks again for the tool!
I have been able to detect the polyA tails with a few datasets.
Now I am working on a relatively large cDNA dataset, which is about 350GB in size.

I have tried to increase the num_cores from 16 to 32 and 64, with 20GB per core.
But I didn't notice big improvement in speed, which means it will need more than 160 hours for our datasets based on the progress in the log file.

Do you have any advice on making it even faster, please?
Thanks!
Jon

**Comment by adnaniazi** [comment]
Hi Jon,

Thanks for using tailfindr.

Sorry to hear about performance issues. Unfortunately it gets slow for big datasets at the moment. I would recommend splitting the big dataset in lets say four folders and then applying tailfindr individually on these folders. Not an optimal solution, I understand. Sorry for that. It is in my todo list to improve performance for large datasets.

Best,
Adnan

**Comment by maximus-sci** [comment]
Have you considered adapting tailfindr to work with SLOW5 files? Nanopolish recently added support for this and it improves performance substantially.

https://www.nature.com/articles/s41587-021-01147-4

https://github.com/hasindu2008/slow5tools

**Comment by adnaniazi** [comment]
It's on my to do list, when I get time for it.

**Comment by jon-xu** [comment]
Thanks Adnan!

We ended up with subsampled the fast5 files.

Will try slow5 when have a chance!

Cheers,

Jon

On 2 Jul 2022, at 01:11, Adnan Niazi ***@***.***> wrote:

﻿

It's on my to do list, when I get time for it.

**Comment by Yang990-sys** [comment]
For multi fast5 files, It's a large time to build index. My program has stopped at this step for a day. I found that the index  matrix is  the correspondence between reads and fast5 files. So if we use single fast5 or summary files genarated by basecalller, speed should be improved. I guess.

**Comment by Yang990-sys** [comment]
SLOW fast5 can speed up nanopolish because it improves the io usage of  fast5. It's different from tailfindr. When data is moved to SSD, nanopolish gets about ten times faster but tailfindr has no change. So I'm guessing that even making  tailfindr for slow5 won't give a huge boost like nanopolish.

**Comment by jon-xu** [comment]
Thanks Adnan!

It’s still manageable - I’ll just let it run and get you updated!

Cheers,

Jon

On May 31, 2022, at 16:30, Adnan Niazi ***@***.***> wrote:

﻿

Hi Jon,

Thanks for using tailfindr.

Sorry to hear about performance issues. Unfortunately it gets slow for big datasets at the moment. I would recommend splitting the big dataset in lets say four folders and then applying tailfindr individually on these folders. Not an optimal solution, I understand. Sorry for that. It is in my todo list to improve performance for large datasets.

Best,
Adnan
