### ISSUE TITLE
calling RNA readswith Guppy

### ISSUE THREAD

**Issue by amir-azizi** [adnaniazi/tailfindr#3]
Hi, 
We have a set of RNA reads that have been called with Guppy. Unfortunately `--hp_correct 1` option was not set for the basecaller. 

I was wondering if this might affect the results from tailfindr.

Thank you.

**Comment by adnaniazi** [comment]
Hi,

No, it is not necessary to have hp_correct option to be set during basecalling for tailfindr to predict the correct poly(A) tail lengths. So you can use tailfindr on your reads as they currently are. They will work fine with tailfindr.
