### ISSUE TITLE
Error in `[[.H5File`(f5_obj, basecaller_path)

### ISSUE THREAD

**Issue by sunsetyerin** [adnaniazi/tailfindr#31]
Hi @adnaniazi,
I got the error below and cannot interpret what is the problem.
Can you please let me know what can I do to run tailfindr?
Thanks in advance.

`
Warning message:
package ‘tailfindr’ was built under R version 4.1.2 
Error in `[[.H5File`(f5_obj, basecaller_path) : 
  An object with name /read_00181928-5546-4115-9249-d9da44b2d809/Analyses/Basecall_1D_001 does not exist in this group
Calls: find_tails ... explore_basecaller_and_fast5type -> [[ -> [[.H5File
Execution halted
Not cleaning up /path/path/.snakemake/scripts/tmpsym8ipb5.tailfindr.R
`

**Comment by adnaniazi** [comment]
Hi, Can you send me the tailfindr command that you are using?

**Comment by sunsetyerin** [comment]
Hi, Adnan,
Thanks for your reply.
I ran trailfindr command in snakemake environment.
Wonder what is causing the problem.
[image: Screen Shot 2022-07-04 at 11.43.21 AM.png]

**Comment by adnaniazi** [comment]
It seems like the snakemake command that is running tailfindr is telling tailfindr to use Basecall_1D_001 group which does not exist in your particular FAST5 files. You need to edit your snakemake command such that it uses Basecall_1D_000 group.

**Comment by adnaniazi** [comment]
Just read the snakemake pipeline and change Basecall_1D_001 to Basecall_1D_000

**Comment by sunsetyerin** [comment]
Thanks, I will try that and let you know if it works okay.
