### ISSUE TITLE
empty csv after analysis

### ISSUE THREAD

**Issue by xcarmengrandix** [adnaniazi/tailfindr#33]
Hello,

I'm facing the same problem other people already reported, but cannot fix it. 
After running tailfindr the analysis ends without errors:

☰ You have configured tailfindr as following:
❯ fast5_dir:         C:/data_nanopore/PA_CG1_081/HEK293T17_polyA_GFP50tail/20220719_1149_MN40636_FAT95703_19084a4c/basecalled_new/test
❯ save_dir:          C:/data_nanopore/PA_CG1_081/HEK293T17_polyA_GFP50tail/20220719_1149_MN40636_FAT95703_19084a4c/tailfindr_test
❯ csv_filename:      rna_tails.csv
❯ num_cores:         4
❯ basecall_group:    Basecall_1D_000
❯ save_plots:        TRUE
❯ plot_debug_traces: FALSE
❯ plotting_library:  rbokeh
── Processing started at 2022-07-25 17:16:27 ───────────────────────────────────────────────────────────────────────────────────
• Searching for all Fast5 files...
  Done! Found 1 Fast5 files.
• Analyzing a single Fast5 file to assess if your data 
  is in an acceptable format...
  ✔ The data has been basecalled using Guppy.
  ✔ Flipflop model was used during basecalling.
  ✔ The reads are packed in multi-fast5 file(s).
  ✔ The experiment type is RNA, so we will search
    for poly(A) tails.
  ✔ The reads are 1D reads.
• Starting a parallel compute cluster...
  Done!
• Discovering reads in the 1 multifast5 files...
  Done! Found 4000 reads
• Searching for Poly(A) tails...
  Processing chunk 1 of 1
• Formatting the tail data...
  Done!
• Saving the data in the CSV file...
  Done! Below is the path of the CSV file:
  C:/data_nanopore/PA_CG1_081/HEK293T17_polyA_GFP50tail/20220719_1149_MN40636_FAT95703_19084a4c/tailfindr_test/rna_tails.csv
• A logfile containing all this information has been saved in this path: 
  C:/data_nanopore/PA_CG1_081/HEK293T17_polyA_GFP50tail/20220719_1149_MN40636_FAT95703_19084a4c/tailfindr_test/2022-07-25_17-16-27_tailfinder.log
── Processing ended at 2022-07-25 17:16:56 
✔ tailfindr finished successfully!

However the csv file doesn't contain any tail and I assume it's because of a wrong installation of the plugin VBZ. I installed it on Windows from nanopore: https://github.com/nanoporetech/vbz_compression/releases/tag/v1.0.1
I then export the path like this:  set HDF5_PLUGIN_PATH=C:\Program Files\OxfordNanopore\ont-vbz-hdf-plugin\hdf5\lib\plugin
but the output doesn't change. 

I'm not sure if I'm doing something wrong in setting the path but I can't manage to make it work. 

Thanks a lot in advance for your help!

**Comment by adnaniazi** [comment]
Hi,

Thank you for trying out tailfindr.

I am sorry; I am not a Windows user, so I dont know how to make the VBZ HDF plugin work in Windows. You can try asking the developers of VBZ plugin on their GitHub.

Adnan

**Comment by xcarmengrandix** [comment]
Hi,

I actually managed to solve the problem in a very simple way by installing the last version of HDF5 with Windows 10 64-bit pre-built binary (https://portal.hdfgroup.org/display/support/HDF5+1.10.9#files).

The link you provide in the readme redirects to a manual installation (https://github.com/mannau/h5-libwin). It was a bit confusing for me.

I'm now curious to analyse my data! :)
