### ISSUE TITLE
connections fails when running find_tails

### ISSUE THREAD

**Issue by yeroslaviz** [adnaniazi/tailfindr#36]
Hi,

I don't think this is a problem with the package,  but I would like to know, if you encounter such a problem.

When I run the `find_tails` command it breaks after a few files, randomly, each time after a different number of files. 

```
> df <- find_tails(fast5_dir = fast5,
+                  save_dir = "Analysis/Nanopore_06.2022/tailfindr",
+                  csv_filename = 'FAT11673_tailfindr.csv',
+                  num_cores = 24,
+                  basecall_group = 'Basecall_1D_000'
+                  )
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
── Started tailfindr (version 1.3) ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
☰ You have configured tailfindr as following:
❯ fast5_dir:         rawData/Nanopore_06.2022/fast5/fastq2/workspace/
❯ save_dir:          Analysis/Nanopore_06.2022/tailfindr
❯ csv_filename:      FAT11673_tailfindr.csv
❯ num_cores:         24
❯ basecall_group:    Basecall_1D_000
❯ save_plots:        FALSE
❯ plot_debug_traces: FALSE
❯ plotting_library:  rbokeh
── Processing started at 2022-09-08 11:54:46 ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
• Searching for all Fast5 files...
  Done! Found 585 Fast5 files.
• Analyzing a single Fast5 file to assess if your data
  is in an acceptable format...
  ✔ The data has been basecalled using Guppy.
  ✔ Flipflop model was used during basecalling.
  ✔ The reads are packed in multi-fast5 file(s).
  ✔ The experiment type is RNA, so we will search
    for poly(A) tails.
  ✔ The reads are 1D reads.
• Starting a parallel compute cluster...
  Done!
• Discovering reads in the 585 multifast5 files...


  Done! Found 2337798 reads
• Searching for Poly(A) tails...
  Processing chunk 1 of 585
  |======================================================================| 100%
  Processing chunk 2 of 585
  |======================================================================| 100%
  Processing chunk 3 of 585
  |======================================================================| 100%
  Processing chunk 4 of 585
  |======================================================================| 100%
  Processing chunk 5 of 585
  |=============================================================         |  87%Error in unserialize(socklist[[n]]) : 'connection' must be a connection
```

Have you seen something like that before? 

Any ideas how to solve it?

thanks
Assa

**Comment by adnaniazi** [comment]
Hi,

I have seen it before. Its most probably because a core may not be available. In this case try reducing the number if cores.

Adnan

**Comment by yeroslaviz** [comment]
I have tried t even with only one core on the cluster, but it still gave me the same error. Is there a way around it?

Does it make sense to maybe break the run into subsets? I have 585 fast5 files. 

On one cluster I used only one core and the run broke after 25 files.

```
> df <- find_tails(fast5_dir = fast5,
+                  save_dir = "Analysis/Nanopore_06.2022/tailfindr",
+                  csv_filename = 'FAT11673_tailfindr.csv',
+                  num_cores = 1,
+                  basecall_group = 'Basecall_1D_000'
+                  )
── Started tailfindr (version 1.3) ─────────────────
☰ You have configured tailfindr as following:
❯ fast5_dir:         rawData/Nanopore_06.2022/fast5/fastq2/workspace/
❯ save_dir:          Analysis/Nanopore_06.2022/tailfindr
❯ csv_filename:      FAT11673_tailfindr.csv
❯ num_cores:         1
❯ basecall_group:    Basecall_1D_000
❯ save_plots:        FALSE
❯ plot_debug_traces: FALSE
❯ plotting_library:  rbokeh
── Processing started at 2022-09-08 14:46:37 ───
• Searching for all Fast5 files...
  Done! Found 585 Fast5 files.
• Analyzing a single Fast5 file to assess if your data
  is in an acceptable format...
  ✔ The data has been basecalled using Guppy.
  ✔ Flipflop model was used during basecalling.
  ✔ The reads are packed in multi-fast5 file(s).
  ✔ The experiment type is RNA, so we will search
    for poly(A) tails.
  ✔ The reads are 1D reads.
• Starting a parallel compute cluster...
  Done!
• Discovering reads in the 585 multifast5 files...
  Done! Found 2337798 reads
• Searching for Poly(A) tails...
  Processing chunk 1 of 585
  |======================================================================| 100%
  Processing chunk 2 of 585
  |======================================================================| 100%

...
  |======================================================================| 100%
  Processing chunk 25 of 585
  |=                                                                     |   1%Error in unserialize(socklist[[n]]) : 'connection' must be a connection
```

The second run on a bigger cluster was ran with 4 cores, but was also interrupted after 125 files.

**Comment by adnaniazi** [comment]
Hi,

In the tailfindr command you can specify a vector of fast5 file paths instead of specifying the directory. This way you can control the number of files that are being processed by tailfindr in a given run.

So using it like this:
file_vec = c('absolute_file_path1.fast5', 'absolute_file_path2.fast5' )
> df <- find_tails(fast5_dir = file_vec,
+                  save_dir = "Analysis/Nanopore_06.2022/tailfindr",
+                  csv_filename = 'FAT11673_tailfindr.csv',
+                  num_cores = 1,
+                  basecall_group = 'Basecall_1D_000'
+                  )

The above.command will then process only the two fast5 files listed in file_vec.

So in this way you can programmatically run tailfindr again and again on small subsets of your data.

**Comment by yeroslaviz** [comment]
Ok, I splitted it into six parts a ~100 files.

I wonder is this somehow might influence the detected lengths of the the tails. 

I can see, that I have different numbers of reads detected in each of the subsets. I guess this has to do with the fact that i have different fast5 files in each. 

BUT, would this influence the results in any way?

thanks for the help
Assa

**Comment by adnaniazi** [comment]
No, it does make a difference. 

Adnan

**Comment by yeroslaviz** [comment]
What difference does it make then? 

Does it make sense to split them if it makes a difference?

**Comment by adnaniazi** [comment]
By splitting your data files, you are just reducing the chance that the chances of the problem that you were facing with one of the core crashing and the whole program crashing with it will reduce.

**Comment by yeroslaviz** [comment]
ok, but you wrote above that it makes a different.This is why I asked again

**Comment by adnaniazi** [comment]
Opps sorry! My bad. I have corrected it now.

**Comment by yeroslaviz** [comment]
thanks

**Comment by yeroslaviz** [comment]
Just wanted to add, that now after splitting the files I could manage to run the whole data set. 

It should be mentioned (or maybe even suggested) in the description, that it is a much faster way to analyze bigger data sets. 

Thanks for the help.
