### ISSUE TITLE
Can you explain the normalization process?

### ISSUE THREAD

**Issue by yeroslaviz** [adnaniazi/tailfindr#37]
i was wondering how `tailfindr` calculate the average nucleotide translocation rate, which is the value used for the normalization. 

I read the paper, but don't really understand what it means, `samples per nucleotide`. What does one regards here as sample? are these the single, unique reads mapped at each specific nucleotide position?

thanks

**Comment by adnaniazi** [comment]
You can find the information about samples_per_nt here: https://adnaniazi.com/website-assets/niazi_and_krause_2019_springer_book_chapter.pdf
