### ISSUE TITLE
Missing entry in .csv output file

### ISSUE THREAD

**Issue by jchang97** [adnaniazi/tailfindr#39]
Hi there, 

My output .csv file looks great, except for one line where some values are missing (highlighted below):

![image](https://user-images.githubusercontent.com/41040156/192430354-469c3614-9dfc-4bda-b2f6-2c5adb3b4445.png)

Could you please help me understand what might be going on here? 

Thank you very much!

**Comment by adnaniazi** [comment]
Hi,

This a read for which tailfindr algorithm crashed because the signal doesn't look as expected by the tailfindr algorithm.

Best,
Adnan

**Comment by jchang97** [comment]
Thank you very much Adnan!
