### ISSUE TITLE
Gene/transcript IDs annotation support?

### ISSUE THREAD

**Issue by sunsetyerin** [adnaniazi/tailfindr#42]
Hi @adnaniazi,
I was able to generate output table.
But wonder how can I get the gene or transcript IDs.

**Comment by adnaniazi** [comment]
Hi @sunsetyerin,

There is an undocumented function in tailfindr that you can use for that purpose. It is called annotate_tails.

Use it like this

annotate_tails(sam_file,
                           tails_csv_file,
                           output_file)

where sam_file is the alignment of your reads with your reference in SAM format. tails_csv_file is the output of the tailfindr containing tail lengths. output_file is the full filepath for the file in which the new result should be stored.
