### ISSUE TITLE
Your data has been basecalled with MinKNOW

### ISSUE THREAD

**Issue by ssomalra** [adnaniazi/tailfindr#45]
Hello,

Prior to running Tailfindr, I have basecalled my fast5 files using Guppy using the following command: 
`guppy_basecaller -i 20190417_2206_MN29158_FAK51077_af7b82e6/fast5_pass -s guppy_out --flowcell FLO-MIN106 --kit SQK-RNA002 --fast5_out --num_callers 2 --cpu_threads_per_caller 1`

After running Tailfindr, I came across an error, as shown below. I verified my files on HDFView and it looks my files do not have the Basecall_1D_101 section, even though I believe I have basecalled using a standalone Guppy. 

Any help regarding the error would be much appreciated. Thank you.

<img width="561" alt="Screen Shot 2023-02-09 at 2 12 16 PM" src="https://user-images.githubusercontent.com/116883221/217914783-43766cd1-aeff-4e7d-8fc7-56298bf6e4e2.png">

**Comment by adnaniazi** [comment]
Hi, please send me one of your basecalled fast5 file. I will have a look at it.

**Comment by ssomalra** [comment]
Sent! Thank you.

**Comment by adnaniazi** [comment]
Hi,
I checked the fast5 file that you sent me. It seems like it was basecalled by MinKNOW's Live basecalling, and not by the standalone Guppy basecaller. Please basecall you reads using the standalone basecaller, and then use tailfindr on the resulting FAST5 files. You will need to use basecall_group = 'Basecall_1D_001' in your tailfindr command.

**Comment by ssomalra** [comment]
Sorry, what do you mean by 'standalone' basecaller?

**Comment by adnaniazi** [comment]
There are two ways to basecall: 1. during data acquisition by Minknow which uses an integrated guppy basecaller, and  2. after the data has been acquired using a standalone installation of guppy. 

You can download and install standalone guppy if you have access to nanopore community website. There you can find the installer for guppy.

**Comment by ssomalra** [comment]
Okay, thank you. Earlier you mentioned using an older guppy version. Which version do you recommend for the --fast5_out flag to work?

**Comment by adnaniazi** [comment]
Any version below v 6.3.2

**Comment by ssomalra** [comment]
I was able to get the output files from Tailfindr after basecalling my fast5 files with an older version of Guppy. Thank you for the help!
