### ISSUE TITLE
No plots are created after successful run

### ISSUE THREAD

**Issue by sandaruwanrat** [adnaniazi/tailfindr#47]
Hi,
There are no plots generated after successful run (it creates a plots directory). I have tried with both 'rbokeh' and 'ggplot2' with " save_plots = TRUE"

Also there was a warning 

✔ tailfindr finished successfully!
Warning message:
`cols` is now required when using `unnest()`.
ℹ Please use `cols = c(read_id, read_type, tail_is_valid, tail_start, tail_end, samples_per_nt, tail_length, file_path,
  has_precise_boundary)`. 

Thank you !

**Comment by adnaniazi** [comment]
Mot probably the csv is also empty. Did you install the vbz plugin.

**Comment by sandaruwanrat** [comment]
Thank for the quick response.

The csv file is not empty (it is a complete output for all the reads with polyA deatils). However, I have installed tailfinder using

"conda install -c bioconda r-tailfindr"

I thought it is installing all the dependencies. I think I may have to install vbz plugin separately.

Thank you very much.

**Comment by sandaruwanrat** [comment]
I  have installed vbz plugin and tired again. However, it still does not create plots.

**Comment by adnaniazi** [comment]
Can you send me the command that you are using?

**Comment by sandaruwanrat** [comment]
Following is the command I used

`df <- find_tails(fast5_dir = '/user/POLYA_call/fast5',
                 save_dir = '/user/tfindr_ana',
                 csv_filename = 'test_cdna_tails.csv',
                 num_cores = 56,
                 dna_datatype = 'custom-cdna',
                 front_primer = "GGTATCAACGCAGAGTACATGGG",
                 end_primer = "CTGTAGGCACCATCAAT",
                 save_plots = TRUE,
                 plotting_library = 'rbokeh')`

Thank you !

**Comment by adnaniazi** [comment]
I have no idea. Never encountered this problem before. May be it could be issue with permissions on the plots folder.  Can you check the permission on the plots folder and its parent folder?

**Comment by sandaruwanrat** [comment]
Thank you very much. I had to change the permissions to get it to work.
