### ISSUE TITLE
poly a tail content 

### ISSUE THREAD

**Issue by sunsetyerin** [adnaniazi/tailfindr#49]
Hi @adnaniazi ,
Is there any chance I can get the content of poly-A tail?
For example, AAAAA, AAAAU, AAAUU, etc.

**Comment by adnaniazi** [comment]
Hi,

Please install tailfindr from `gregor_polya_base_end` branch. You will then the contents of the polyA tail as well. This is an old branch and not upto date with the main branch, but it produces the polyA tail content.

Best,
Adnan
