### ISSUE TITLE
all reads invalid

### ISSUE THREAD

**Issue by rgjain** [adnaniazi/tailfindr#51]
Hi Adnan,
I am using tailfindr and my kit is Rapid sequencing DNA V14 - barcoding (SQK-RBK114.24). I did fast-5 output using Guppy-6.3.8 and installed vbz plugins as well. However, I am getting the attached output after tailfindr analysis.

![MicrosoftTeams-image](https://github.com/adnaniazi/tailfindr/assets/134037178/5ce3ff77-ad56-4738-96cc-43f8fc5e63d9)
![image](https://github.com/adnaniazi/tailfindr/assets/134037178/5c882245-147a-4bbb-ad0a-1a1e0cb9572a)

**Comment by rgjain** [comment]
Hi Adnan,

Thank you for your email.

Is there any other software or script that works with DNA poly A tail?

Cheers,
Ritesh
________________________________

**Comment by adnaniazi** [comment]
Hi,

No, sorry. I don't know any.

Adnan
