### ISSUE TITLE
Error in explore_basecaller_and_fast5type(fast5_files_list[1], basecall_group = basecall_group) :

### ISSUE THREAD

**Issue by Aimepicornell** [adnaniazi/tailfindr#60]
Hello, Unfortunately i cant seem to make tailfindr work. Do you maybe see what the problem could be in my log?

Thank you very much in advance

Aime Picornell

── Started tailfindr (version 1.4) ─────────────────────────────────────────────────────
────────────────────────────────────────────────────────────────────────────────────────
☰ You have configured tailfindr as following:
❯ fast5_dir:         /home/ubuntu/Desktop/Aime/AnalyzeFAAR_09_2023/Tailfindr
❯ save_dir:          /home/ubuntu/Desktop/Aime/AnalyzeFAAR_09_2023/Tailfindr
❯ csv_filename:      Frna_tails.csv
❯ num_cores:         12
❯ basecall_group:    Basecall_1D_000
❯ save_plots:        FALSE
❯ plot_debug_traces: FALSE
❯ plotting_library:  rbokeh
── Processing started at 2023-09-11 09:09:01 ───────────────────────────────────────────
• Searching for all Fast5 files...
  Done! Found 1 Fast5 files.
• Analyzing a single Fast5 file to assess if your data 
  is in an acceptable format...
Error in explore_basecaller_and_fast5type(fast5_files_list[1], basecall_group = basecall_group) : 
  object 'model' not found
In addition: Warning message:
In .Internal(gc(verbose, reset, full)) :
  closing unused connection 4 (/home/ubuntu/Desktop/Aime/AnalyzeFAAR_09_2023/Tailfindr/2023-09-11_09-07-43_tailfinder.log)

**Comment by adnaniazi** [comment]
Hi,

It seems like your FAST5 is not basecalled. You need to basecall it and produce a basecalled FAST5 file using Guppy (version < 6.3.2) using the --fast5_out option during basecalling. Use these basecalled FAST5 files as input to tailfindr.

**Comment by Aimepicornell** [comment]
Thanks for the reply! Unfortunately i am struggling to install an older version of guppy. Do you have any advice how to do it? I have a windows and ubuntu computer available!

**Comment by adnaniazi** [comment]
Use guppy on linux. That would be the easiest way to go about it. Download the guppy tar file, extract it, and then use it.

**Comment by Aimepicornell** [comment]
Hey, I managed to make it work! Thank you so much for your time to help me with my beginner issues. Greetings from Cologne Germany and all the best to you!
