### ISSUE TITLE
Use of tailfindr starting from fast5 without basecalling data

### ISSUE THREAD

**Issue by aduclert** [adnaniazi/tailfindr#63]
Hello,

I'd like to use tailfindr starting from fast5 files, but my fast5 files do not have any Analyses group with fastq data in it, and this seems to be a requirement for tailfindr. However, I couldn't find how to do that with the current version of guppy.
Do you have any idea of how to do use tailfindr in such a situation ?

Thanks a lot.

Aymeric Duclert

**Comment by adnaniazi** [comment]
Hi, 
Please use guppy version <= v6.3.4 and set the --fast5_out option during basecalling.
Adnan

**Comment by aduclert** [comment]
Thanks for you answer.
For those that might be interested, I struggled to find older version of guppy since no link from Nanopore site.
I finally could download it with :
https://mirror.oxfordnanoportal.com/software/analysis/ont-guppy_6.3.4_linux64.tar.gz
