### ISSUE TITLE
Bug in gregor_polya_base_end branch

### ISSUE THREAD

**Issue by theottlo** [adnaniazi/tailfindr#9]
Hi, I was interested in finding the polyA start/end position in the reads and came across a similar issue: #7. This led me to the branch that you made for him, `gregor_polya_base_end`. I tried running it and noticed that there seems to be a bug. The length of the polyA determined by the basecaller can be calculated from the `tail_start_base_index` and `tail_end_base_index`, but this doesn't match the length of `polya_tail_fasta_seq`. In fact, the length of `polya_tail_fasta_seq` is always 5nt longer than `tail_start_base_index` - `tail_end_base_index`. 

In the example below, you can see that the lengths calculated from the `tail_start_base_index` and `tail_end_base_index` are 10, 8, 0, 5 but the corresponding lengths from `polya_tail_fasta_seq` are 15, 13, 5, 10, respectively.
![tailfindr_branch_bug](https://user-images.githubusercontent.com/33464594/73986666-0cf72e00-48f3-11ea-9e62-d874808360a7.png)

**Comment by adnaniazi** [comment]
Hi,

Thank you for highlighting the bug. 

You are indeed right. It seems like polya_tail_fasta_seq is always 5 bigger than the difference of the end indices. Can you please email me four or five of your reads. I would like to investigate it on your reads, because I didn't see the problem with my reads. May be something is different between our basecaller versions. You can email them to me on adnaniazi@gmail.com. Thank you.

**Comment by theottlo** [comment]
Sure, I just sent you an email! Thanks for looking into this and let me know if you need anything else!

**Comment by adnaniazi** [comment]
Hi Theodora,

I have now fixed the bug. Please uninstall `tailfindr` and install the same branch (`gregor_polya_base_end`) again. Feel free to let me know if you encounter any further issues.

Adnan

**Comment by theottlo** [comment]
Great, thanks again for the quick fix Adnan! I'll let you know if I encounter any further issues.

**Comment by theottlo** [comment]
Hey Adnan, I noticed that the position of the polyA in the reads is not output for cDNA. If it isn't too much trouble, I was wondering whether you could add this functionality into the branch (`gregor_polya_base_end`) as well.

**Comment by adnaniazi** [comment]
Hi,
Yes, I will start working on it today. I will let you know when it is ready.
Adnan

**Comment by theottlo** [comment]
Great, thank you so much!

**Comment by adnaniazi** [comment]
Hi,

I have fixed the issue. Please install the branch again, and run it on your cDNA reads. Feel free to let me know if there are any issues.

Best,
Adnan

**Comment by theottlo** [comment]
Hi Adnan,

Thanks again for adding polyA detection in cDNA reads. I ran it, but came across this small error when formatting the tail data:
```
Error: No common type for `..1$tail_start_base_index$tail_start_base_index` <character> and `..5$tail_start_base_index$tail_start_base_index` <integer>.
Backtrace:
     █
  1. ├─tailfindr::find_tails(...)
  2. │ └─tidyr::unnest(result)
  3. │   ├─tidyr::unnest(...)
  4. │   └─tidyr:::unnest.data.frame(...)
  5. │     └─tidyr::unchop(data, !!cols, keep_empty = keep_empty, ptype = ptype)
  6. │       └─vctrs::vec_rbind(!!!x, .ptype = ptype)
  7. ├─vctrs:::vec_type2_dispatch(x = x, y = y, x_arg = x_arg, y_arg = y_arg)
  8. ├─vctrs::vec_ptype2.character(x = x, y = y, x_arg = x_arg, y_arg = y_arg)
  9. └─vctrs:::vec_ptype2.character.default(...)
 10.   └─vctrs::vec_default_ptype2(x, y, x_arg = x_arg, y_arg = y_arg)
 11.     └─vctrs::stop_incompatible_type(x, y, x_arg = x_arg, y_arg = y_arg)
 12.       └─vctrs:::stop_incompatible(...)
 13.         └─vctrs:::stop_vctrs(...)
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
```

**Comment by adnaniazi** [comment]
Hi Theodora,

Can you email me some of the data that you are working on. If your data is single read fast5 files, then please send me around 20 of the reads; if your data is as multiread fast5 file, then I only one of such multiread files. I will then debug my code.

Thanks.

Adnan

**Comment by adnaniazi** [comment]
Hi,

Thanks for emailing those Fast5 files. I have now fixed the bug. Please uninstall and install again from the branch. Again, please feel free to let me know if you encounter any further issues.

Best,
Adnan
